# Normal DevOps Pipeline
Code → Build → Test → Security → Package → Deploy

# DevSecOps Pipeline
Code → SAST → Dependency Scan → Build → Image Scan → Deploy


#### Application
const express = require('express');
const app = express();

app.get('/', (req, res) => {
  res.send('Hello DevSecOps!');
});

app.listen(3000, () => console.log('App running'));


# Dockerfile
# Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY app.js app.js

# Stage 2: Production
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app /app

# Creating a non root user
RUN addgroup appgroup && adduser -S appuser -G appgroup
USER appuser

# Running the Application
CMD ["node", "app.js"]


############################################################

# Create sonar-project.properties file
sonar.projectKey=your_project
sonar.organization=your_org
sonar.host.url=https://sonarcloud.io

# Click on analyze new project and
# select github repo 


# For disabling analysis method 
# go to settings -> Analysis Method -> Disable


# Pipeline
name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run app
        run: echo "App running..."


    # Extend It -- SAST
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Fetch it from sonarqube cloud


    # Filesystem Scanning --- SCA
    # run: npm audit --audit-level=high
    - name: Run Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    - name: Build Docker Image
      run: docker build -t demo-app .

    # Image Scanning
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'demo-app'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
    
    # Secrets Scanning  
    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2

    # Misconfiguration Scan (VERY IMPRESSIVE PART)
    - name: Trivy Config Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        severity: 'HIGH,CRITICAL'

    # DAST 
    - name: OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://example.com'

      
# intentionally fail gitleaks
# create secrets.env
API_KEY=chehfe33uhfu29di0q1

