Open Policy Agent (OPA): A policy engine used to enforce rules.
Gatekeeper: A Kubernetes admission controller built on OPA.
Together, they let you block unsafe configurations before they get deployed.

ConstraintTemplate → rule definition
Constraint → rule applied

# create kind cluster
# install gatekeeper
kubectl get pods -n gatekeeper-system

---- “We just added a security layer to Kubernetes”

# Deploy NORMAL app
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx


# Add POLICY
--- Rule: “No root containers allowed”

# ConstraintTemplate -- Definition
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyrunroot
spec:
  crd:
    spec:
      names:
        kind: K8sDenyRunRoot
  targets:
    # Runs during admission control (when resources are created/updated).
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyrunroot

        violation[{"msg": msg}] {
          input.review.object.spec.containers[_].securityContext.runAsUser == 0
          msg := "Running as root is not allowed"
        }


# Constraint -- Rule Applied - This tells Gatekeeper where to enforce the rule.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyRunRoot  # Uses the template you defined earlier.
metadata:
  name: deny-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]


# Create pod with non root access
kubectl get pod <pod-name> -o yaml > pod.yaml

# OR Change Template
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx
    # non root config
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true


“No latest tag” policy

violation[{"msg": msg}] {
  input.review.object.spec.containers[_].image == "*:latest"
  msg := "latest tag not allowed"
}
