name: Grype Scan

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
          sudo mv ./bin/grype /usr/local/bin/

      - name: Update DB
        run: grype db update

      - name: Scan Image
        run: |
          grype dakshsawhneyy/demo-service-a \
          --fail-on medium \
          -o table
